train_dataset:
  name: dataset.data_val.PolypObjDataset
  params:
    image_root: 'dataset/NC4K/Imgs/'
    gt_root: 'dataset/NC4K/GT/'
    trainsize: 352

test_dataset:
  COD10K:
    name: dataset.data_val.test_dataset
    params:
      image_root: 'dataset/NC4K/Imgs/'
      gt_root: 'dataset/NC4K/GT/'
      testsize: 352
  CAMO:
    name: dataset.data_val.test_dataset
    params:
      image_root: 'dataset/NC4K/Imgs/'
      gt_root: 'dataset/NC4K/GT/'
      testsize: 352
  CHAMELEON:
    name: dataset.data_val.test_dataset
    params:
      image_root: 'dataset/NC4K/Imgs/'
      gt_root: 'dataset/NC4K/GT/'
      testsize: 352
  NC4K:
    name: dataset.data_val.test_dataset
    params:
      image_root: 'dataset/NC4K/Imgs/'
      gt_root: 'dataset/NC4K/GT/'
      testsize: 352
  CDS2K:
    name: dataset.cds2k_dataset.cds2K_dataset
    params:
      root: '/media/datatset/CDS2K'
      testsize: 352